apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    plugin: prometheus
  name: prometheus-monitor
  namespace: kube-system
spec:
  ports:
  - name: prometheus-monitor-0
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP

